src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductAttributeGroupVm.cs
using System.Collections.Generic;

namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductAttributeGroupVm
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public IList<ProductAttributeVm> Attributes { get; set; } = new List<ProductAttributeVm>();
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductAttributeVm.cs
namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductAttributeVm
    {
        public long Id { get; set; }

        public long AttributeValueId { get; set; }

        public string Name { get; set; }

        public string Value { get; set; }

        public string GroupName { get; set; }
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductForm.cs
using System.Collections.Generic;
using Microsoft.AspNet.Http;

namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductForm
    {
        public ProductViewModel Product { get; set; }

        public IFormFile ThumbnailImage { get; set; }

        public IList<IFormFile> ProductImages { get; set; } = new List<IFormFile>();

        public IList<IFormFile> File { get; set; } = new List<IFormFile>();
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductListItem.cs
using System;

namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductListItem
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public DateTime CreatedOn { get; set; }

        public bool IsPublished { get; set; }
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductMediaVm.cs
namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductMediaVm
    {
        public long Id { get; set; }

        public string MediaUrl { get; set; }
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductOptionCombinationVm.cs
namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductOptionCombinationVm
    {
        public long OptionId { get; set; }

        public string OptionName { get; set; }

        public string Value { get; set; }
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductOptionVm.cs
using System.Collections.Generic;

namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductOptionVm
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public IList<string> Values { get; set; } = new List<string>();
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductTemplateFrom.cs
using System.Collections.Generic;

namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductTemplateFrom
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public IList<ProductAttributeVm> Attributes { get; set; } = new List<ProductAttributeVm>();
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductVariationVm.cs
using System.Collections.Generic;

namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductVariationVm
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public decimal PriceOffset { get; set; }

        public IList<ProductOptionCombinationVm> OptionCombinations { get; set; } =
            new List<ProductOptionCombinationVm>();
    }
}

src/Shopcuatoi.Web/Areas/Admin/ViewModels/Products/ProductVm.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Shopcuatoi.Web.Areas.Admin.ViewModels.Products
{
    public class ProductViewModel
    {
        public ProductViewModel()
        {
            IsPublished = true;
        }

        public long Id { get; set; }

        public decimal Price { get; set; }

        public decimal? OldPrice { get; set; }

        [Required]
        public string Name { get; set; }

        public string ShortDescription { get; set; }

        public string Description { get; set; }

        public string Specification { get; set; }

        public bool IsPublished { get; set; }

        public IList<long> CategoryIds { get; set; } = new List<long>();

        public IList<ProductAttributeVm> Attributes { get; set; } = new List<ProductAttributeVm>();

        public IList<ProductOptionVm> Options { get; set; } = new List<ProductOptionVm>();

        public IList<ProductVariationVm> Variations { get; set; } = new List<ProductVariationVm>();

        public string ThumbnailImageUrl { get; set; }

        public IList<ProductMediaVm> ProductMedias { get; set; } = new List<ProductMediaVm>();

        public IList<long> DeletedMediaIds { get; set; } = new List<long>();

        public long? BrandId { get; set; }
    }
}

src/Shopcuatoi.Web/ViewModels/Catalog/ProductsByCategory.cs
using System.Collections.Generic;
using Microsoft.AspNet.Mvc.Rendering;

namespace Shopcuatoi.Web.ViewModels.Catalog
{
    public class ProductsByCategory
    {
        public long CategoryId { get; set; }

        public long? ParentCategorId { get; set; }

        public string CategoryName { get; set; }

        public string CategorySeoTitle { get; set; }

        public int TotalProduct { get; set; }

        public IList<ProductListItem> Products { get; set; } = new List<ProductListItem>();

        public FilterOption FilterOption { get; set; }

        public SearchOption CurrentSearchOption { get; set; }

        public IList<SelectListItem> AvailableSortOptions => new List<SelectListItem>
        {
            new SelectListItem { Text = "Price: Low to High", Value = "price-asc" },
            new SelectListItem { Text = "Price: High to Low", Value = "price-desc" }
        };
    }
}

src/Shopcuatoi.Web/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using Shopcuatoi.Core.ApplicationServices;
using Shopcuatoi.Core.Domain.Models;
using Shopcuatoi.Infrastructure;
using Shopcuatoi.Infrastructure.Domain.IRepositories;
using Shopcuatoi.Web.Areas.Admin.ViewModels.Products;
using Shopcuatoi.Web.Areas.Admin.ViewModels.SmartTable;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Mvc;

namespace Shopcuatoi.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class ProductController : Controller
    {
        private readonly IRepository<Product> productRepository;
        private readonly IMediaService mediaService;
        private readonly IProductService productService;
        private readonly IRepository<ProductCategory> productCategoryRepository;
        private readonly IRepository<ProductOptionValue> productOptionValueRepository;
        private readonly IRepository<ProductAttributeValue> productAttributeValueRepository; 

        public ProductController(
            IRepository<Product> productRepository,
            IMediaService mediaService,
            IProductService productService,
            IRepository<ProductCategory> productCategoryRepository,
            IRepository<ProductOptionValue> productOptionValueRepository,
            IRepository<ProductAttributeValue> productAttributeValueRepository)
        {
            this.productRepository = productRepository;
            this.mediaService = mediaService;
            this.productService = productService;
            this.productCategoryRepository = productCategoryRepository;
            this.productOptionValueRepository = productOptionValueRepository;
            this.productAttributeValueRepository = productAttributeValueRepository;
        }

        public IActionResult Get(long id)
        {
            var product = productRepository.Get(id);

            var productVm = new ProductViewModel
            {
                Id = product.Id,
                Name = product.Name,
                ShortDescription = product.ShortDescription,
                Description = product.Description,
                Specification = product.Specification,
                OldPrice = product.OldPrice,
                Price = product.Price,
                CategoryIds = product.Categories.Select(x => x.CategoryId).ToList(),
                ThumbnailImageUrl = mediaService.GetThumbnailUrl(product.ThumbnailImage),
                BrandId = product.BrandId
            };

            foreach (var productMedia in product.Medias)
            {
                productVm.ProductMedias.Add(new ProductMediaVm
                {
                    Id = productMedia.Id,
                    MediaUrl = mediaService.GetThumbnailUrl(productMedia.Media)
                });
            }

            var options = from opt in product.OptionValues
                             group opt by new
                             {
                                 opt.OptionId,
                                 opt.Option.Name,
                                 opt.ProductId
                             }
                             into g
                             select new ProductOptionVm
                             {
                                 Id = g.Key.OptionId,
                                 Name = g.Key.Name,
                                 Values = g.Select(x => x.Value).Distinct().ToList()
                             };

            productVm.Options = options.ToList();

            foreach (var variation in product.Variations.Where(x => !x.IsDeleted))
            {
                productVm.Variations.Add(new ProductVariationVm
                {
                    Id = variation.Id,
                    Name = variation.Name,
                    PriceOffset = variation.PriceOffset,
                    OptionCombinations = variation.OptionCombinations.Select(x => new ProductOptionCombinationVm
                    {
                        OptionId = x.OptionId,
                        OptionName = x.Option.Name,
                        Value = x.Value
                    }).ToList()
                });
            }

            productVm.Attributes = product.AttributeValues.Select(x => new ProductAttributeVm
            {
                AttributeValueId = x.Id,
                Id = x.AttributeId,
                Name = x.Attribute.Name,
                GroupName = x.Attribute.Group.Name,
                Value = x.Value,
                
            }).ToList();

            return Json(productVm);
        }

        public IActionResult List([FromBody] SmartTableParam param)
        {
            var products = productRepository.Query().Where(x => !x.IsDeleted);
            var gridData = products.ToSmartTableResult(
                param,
                x => new ProductListItem
                    {
                        Id = x.Id,
                        Name = x.Name,
                        CreatedOn = x.CreatedOn,
                        IsPublished = x.IsPublished
                    });

            return Json(gridData);
        }

        [HttpPost]
        public IActionResult Create(ProductForm model)
        {
            if (!ModelState.IsValid)
            {
                return new BadRequestObjectResult(ModelState);
            }

            var product = new Product
            {
                Name = model.Product.Name,
                SeoTitle = StringHelper.ToUrlFriendly(model.Product.Name),
                ShortDescription = model.Product.ShortDescription,
                Description = model.Product.Description,
                Specification = model.Product.Specification,
                Price = model.Product.Price,
                OldPrice = model.Product.OldPrice,
                IsPublished = model.Product.IsPublished,
                BrandId = model.Product.BrandId
            };

            foreach (var option in model.Product.Options)
            {
                foreach (var value in option.Values)
                {
                    product.AddOptionValue(new ProductOptionValue
                    {
                        Value = value,
                        OptionId = option.Id
                    });
                }
            }

            MapProductVariationVmToProduct(model, product);

            foreach (var attribute in model.Product.Attributes)
            {
                var attributeValue = new ProductAttributeValue
                {
                    AttributeId = attribute.Id,
                    Value = attribute.Value
                };

                product.AddAttributeValue(attributeValue);
            }

            foreach (var categoryId in model.Product.CategoryIds)
            {
                var productCategory = new ProductCategory
                {
                    CategoryId = categoryId
                };
                product.AddCategory(productCategory);
            }

            SaveProductImages(model, product);

            productService.Create(product);

            return Ok();
        }

        [HttpPost]
        public IActionResult Edit(long id, ProductForm model)
        {
            if (!ModelState.IsValid)
            {
                return new BadRequestObjectResult(ModelState);
            }

            var product = productRepository.Get(id);
            product.Name = model.Product.Name;
            product.ShortDescription = model.Product.ShortDescription;
            product.Description = model.Product.Description;
            product.Specification = model.Product.Specification;
            product.Price = model.Product.Price;
            product.OldPrice = model.Product.OldPrice;
            product.BrandId = model.Product.BrandId;

            SaveProductImages(model, product);

            foreach (var productMediaId in model.Product.DeletedMediaIds)
            {
                var productMedia = product.Medias.First(x => x.Id == productMediaId);
                mediaService.DeleteMedia(productMedia.Media);
                product.RemoveMedia(productMedia);
            }

            AddOrDeleteProductOption(model, product);

            AddOrDeleteProductVariation(model, product);

            AddOrDeleteProductAttribute(model, product);

            AddOrDeleteCategories(model, product);

            productService.Update(product);

            return Ok();
        }

        private static void MapProductVariationVmToProduct(ProductForm model, Product product)
        {
            foreach (var variationVm in model.Product.Variations)
            {
                var variation = new ProductVariation
                {
                    Name = variationVm.Name,
                    PriceOffset = variationVm.PriceOffset
                };
                foreach (var combinationVm in variationVm.OptionCombinations)
                {
                    variation.AddOptionCombination(new ProductOptionCombination
                    {
                        OptionId = combinationVm.OptionId,
                        Value = combinationVm.Value
                    });
                }

                product.AddProductVariation(variation);
            }
        }

        private void AddOrDeleteCategories(ProductForm model, Product product)
        {
            foreach (var categoryId in model.Product.CategoryIds)
            {
                if (product.Categories.Any(x => x.CategoryId == categoryId))
                {
                    continue;
                }

                var productCategory = new ProductCategory
                {
                    CategoryId = categoryId
                };
                product.AddCategory(productCategory);
            }

            var deletedProductCategories =

src/Shopcuatoi.Web/Components/CategoryBreadcrumbViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Mvc;
using Shopcuatoi.Core.Domain.Models;
using Shopcuatoi.Infrastructure.Domain.IRepositories;
using Shopcuatoi.Web.ViewModels;

namespace Shopcuatoi.Web.Components
{
    public class CategoryBreadcrumbViewComponent : ViewComponent
    {
        private readonly IRepository<Category> categoryRepository;

        public CategoryBreadcrumbViewComponent(IRepository<Category> categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }

        public IViewComponentResult Invoke(IEnumerable<long> categoryIds)
        {
            var breadcrumbs = categoryIds.Select(Create).ToList();

            return View(breadcrumbs.OrderByDescending(x => x.Count).First());
        }

        public IViewComponentResult Invoke(long categoryId)
        {
            var breadcrumbModels = Create(categoryId);

            return View(breadcrumbModels);
        }

        private IList<BreadcrumbViewModel> Create(long categoryId)
        {
            var category = categoryRepository.Get(categoryId);
            var breadcrumbModels = new List<BreadcrumbViewModel>
            {
                new BreadcrumbViewModel
                {
                    Text = category.Name,
                    Url = category.SeoTitle
                }
            };
            var parentCategory = category.Parent;
            while (parentCategory != null)
            {
                breadcrumbModels.Insert(0, new BreadcrumbViewModel
                {
                    Text = parentCategory.Name,
                    Url = parentCategory.SeoTitle
                });
                parentCategory = parentCategory.Parent;
            }

            return breadcrumbModels;
        }
    }
}

src/Shopcuatoi.Web/Views/Product/ProductDetail.cshtml
@using System.Globalization

@model Shopcuatoi.Web.ViewModels.Catalog.ProductDetail

@{
    ViewBag.Title = Model.Name;
}

@section head
{
    <link href="~/lib/smoothproducts/css/smoothproducts.css" rel="stylesheet" />
    <link href="~/css/product-detail.css" rel="stylesheet" />
}

<div>
    <ol class="breadcrumb">
        <li><a href="~/">Home</a></li>
        @if (Model.Categories.Any())
        {
            @await Component.InvokeAsync("CategoryBreadcrumb", Model.Categories.Select(x => x.Id))
        }
        <li><span class="active">@Model.Name</span></li>
    </ol>
</div>

<div class="product-detail">
    <div class="row">
        <div class="col-md-6">
            <div class="sp-wrap">
                @foreach (var image in Model.Images)
                {
                    <a href="@image.Url">
                        <img src="@image.ThumbnailUrl" alt="" />
                    </a>
                }
            </div>
        </div>
        <div class="col-md-6">
            <div class="product-name">
                <h1 class="">@Model.Name</h1>
            </div>
            <ul class="list-inline product-ratings margin-bottom-30">
                <li><i class="rating-selected fa fa-star"></i></li>
                <li><i class="rating-selected fa fa-star"></i></li>
                <li><i class="rating-selected fa fa-star"></i></li>
                <li><i class="rating fa fa-star"></i></li>
                <li><i class="rating fa fa-star"></i></li>
                <li class="product-review-list">
                    <span>(1) <a href="#">Review</a> | <a href="#"> Add Review</a></span>
                </li>
            </ul>
            <div class="product-short-desc">@Html.Raw(Model.ShortDescription)</div>
            <div class="product-price">
                <h3>@Model.Price.ToString("N0", new CultureInfo("vi-VN")) VND</h3>
            </div>
            <form>
                <input type="hidden" name="productId" value="@Model.Id"/>
                @if (Model.HasVariation)
                {
                    <div class="product-attrs">
                        @foreach (var option in Model.AvailableOptions)
                        {
                            <div>
                                <h4>@option.OptionName </h4>
                                <ul class="list-inline product-attr-options">
                                    @foreach (var value in option.Values)
                                    {
                                        var shouldChecked = value == option.Values.First();
                                        <li>
                                            <input type="radio" value="@value" checked="@shouldChecked" name="@option.OptionName"/>
                                            <label>@value</label>
                                        </li>
                                    }
                                </ul>
                            </div>
                        }
                    </div>
                }
                <div class="add-to-cart">
                    <div class="product-quantity">
                        <button type="button" class="quantity-button" name="subtract" value="-">-</button>
                        <input type="text" class="quantity-field" name="qty" value="1">
                        <button type="button" class="quantity-button" name="add" value="+">+</button>
                    </div>

                    <button type="button" class="btn btn-lg btn-add-cart">Add to Cart</button>
                </div>
            </form>
            <div>
                <ul class="list-inline add-to-wishlist">
                    <li class="wishlist-in">
                        <i class="fa fa-heart"></i>
                        <a href="#">Add to Wishlist</a>
                    </li>
                    <li class="compare-in">
                        <i class="fa fa-exchange"></i>
                        <a href="#">Add to Compare</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    @if (!String.IsNullOrWhiteSpace(Model.Description))
    {
        <div>
            <h3>Product detail</h3>
            @Html.Raw(Model.Description)
        </div>
    }

    @if (!String.IsNullOrWhiteSpace(Model.Specification))
    {
        <div>
            <h3>Product specification</h3>
            @Html.Raw(Model.Specification)
        </div>
    }
    @if (Model.Attributes.Any())
    {
        <div>
            <h3>Product specification</h3>
            <table class="table table-striped">
                @foreach (var attribute in Model.Attributes)
                {
                    <tr>
                        <td>@attribute.Name</td>
                        <td>@attribute.Value</td>
                    </tr>
                }
            </table>
        </div>
    }
</div>

@section scripts
{
    <script src="~/lib/smoothproducts/js/smoothproducts.js"></script>
    <script src="~/js/product-detail.js"></script>
    <script src="~/js/cart/add-to-cart.js"></script>
}

src/Shopcuatoi.Web/Views/Product/ProductsByCategory.cshtml
@using System.Threading.Tasks
@using Shopcuatoi.Web.ViewModels.Catalog

@model ProductsByCategory
@{
    ViewBag.Title = Model.CategoryName;
}

@section head {
    <link href="~/lib/nouislider/nouislider.min.css" rel="stylesheet" />
}

<div>
    <ol class="breadcrumb">
        <li><a href="~/">Home</a></li>
        @if (Model.ParentCategorId.HasValue)
        {
            @await Component.InvokeAsync("CategoryBreadcrumb", Model.ParentCategorId.Value)
        }
        <li><span class="active">@Model.CategoryName</span></li>
    </ol>
</div>
<div class="row">
    <div class="col-md-3 product-list-filters">
        <h3>Filter by</h3>
        <form id="productFilter" name="productFilter" method="GET" action="~/@Model.CategorySeoTitle">
            <div class="panel-group" id="accordion-brand">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion-brand" href="#collapse-brand">
                                Brands
                                <i class="fa fa-angle-down"></i>
                            </a>
                        </h2>
                    </div>
                    <div id="collapse-brand" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <ul class="list-unstyled checkbox-list">
                                @foreach (var brand in Model.FilterOption.Brands)
                                {
                                    <li>
                                        <label class="checkbox">
                                            <input type="checkbox" value="@brand.SeoTitle" name="brand" checked="@Model.CurrentSearchOption.GetBrands().Contains(brand.SeoTitle)">
                                            @brand.Name
                                            <small>(@brand.Count)</small>
                                        </label>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-group" id="accordion-price">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion-price" href="#collapse-price">
                                Price
                                <i class="fa fa-angle-down"></i>
                            </a>
                        </h2>
                    </div>
                    <div id="collapse-price" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <div id="priceSlider"></div>
                            <div>
                                <input type="hidden" id="originMinPrice" value="@Model.FilterOption.Price.MinPrice.ToString("F0")"/>
                                <input type="hidden" id="originMaxPrice" value="@Model.FilterOption.Price.MaxPrice.ToString("F0")" />
                                <span id="minPrice"></span>
                                <span id="maxPrice"></span>
                            </div>
                            <div class="price-actions">
                                <button id="reset-price" type="button" class="btn btn-default">Reset</button>
                                <button id="apply-price" type="button" class="btn btn-default">Apply</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-9">
        <div class="row">
            <div class="col-sm-6 category-result">
                <h2>@Model.CategoryName</h2>
                <small class="badge-results">@Model.TotalProduct Results</small>
            </div>
            <div class="col-sm-6">
                <ul class="list-inline clear-both product-list-display-options">
                    <li class="show-option">
                        <a href="#"><i class="fa fa-th-list"></i></a>
                        <a href="#"><i class="fa fa-th"></i></a>
                    </li>
                    <li class="sort-by">
                        <label>Sort By :</label>
                        <div class="btn-group">
                            <select asp-for="CurrentSearchOption.Sort" asp-items="Model.AvailableSortOptions" class="form-control"></select>
                        </div>
                    </li>
                    @*<li class="pagination-option">
                        <label>Show :</label>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                20 <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">All</a></li>
                                <li><a href="#">50</a></li>
                                <li><a href="#">30</a></li>
                            </ul>
                        </div>
                    </li>*@
                </ul>
            </div>
        </div>
        @await Html.PartialAsync("ProductList", new ProductList(Model.Products))
    </div>
</div>

@section scripts {
    <script src="~/lib/wnumb/wnumb.js"></script>
    <script src="~/lib/nouislider/nouislider.min.js"></script>

    <script>
        var productFilter = {};
        productFilter.currentSearchOption = @Html.Raw(Model.CurrentSearchOption.ToJson());
        productFilter.priceSetting = {
            min: @Model.FilterOption.Price.MinPrice,
            max: @Model.FilterOption.Price.MaxPrice,
            currentMin: @(Model.CurrentSearchOption.MinPrice ?? Model.FilterOption.Price.MinPrice),
            currentMax: @(Model.CurrentSearchOption.MaxPrice ?? Model.FilterOption.Price.MaxPrice)
        };
    </script>
    <script src="~/js/product-filter.js"></script>
}